services:
  mongodb:
    image: mongo:7
    container_name: supportflow-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend-spring
    container_name: supportflow-backend
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/supportflow
      SUPPORTFLOW_AI_CLASSIFICATION_BASE_URL: http://ai-service:8000
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - ai-service

  ai-service:
    build:
      context: ./ai-service-python
    container_name: supportflow-ai-service
    ports:
      - "8000:8000"

  redis:
    image: redis:7
    container_name: supportflow-redis
    ports:
      - "6379:6379"

volumes:
  mongo-data:
